# TensoRoom Configuration file

#Hardware Options
#device: "cuda"
device: "mps"
dtype: "float16"

# Diffusion Model Options
model_id: "stabilityai/sdxl-turbo"
prompt: "A cozy modern living room with large windows, and warm lighting. The room is decorated with contemporary furniture and has a comfortable atmosphere."
output_dir: "data/images/output.png"
steps: 1
seed: 42

#Segmentation Model Options
box_threshold: 0.3
text_threshold: 0.15