"""
Tests for the output watermark and metadata
===========================================

What these cover
----------------
``src/branding.py`` is plain Pillow, so these run on any machine::

    uv run pytest tests/test_branding.py

They check the watermark lands only in the bottom-right corner, at the same
relative size on any image, and that saved PNGs say they were generated by
TensorRoom.
"""

import io

import numpy as np
from PIL import Image

from src import branding


def _changed(before: Image.Image, after: Image.Image) -> np.ndarray:
    return np.any(np.asarray(before) != np.asarray(after), axis=-1)


def test_watermark_only_touches_bottom_right():
    photo = Image.new("RGB", (1600, 1200), (40, 60, 80))
    marked = branding.watermark(photo)
    assert marked.size == photo.size and marked.mode == "RGB"
    changed = _changed(photo, marked)
    ys, xs = np.nonzero(changed)
    assert len(xs) > 0
    assert xs.min() > photo.width * 0.85 and ys.min() > photo.height * 0.8
    assert xs.max() < photo.width and ys.max() < photo.height


def test_watermark_scales_with_image():
    def mark_width(w, h):
        photo = Image.new("RGB", (w, h), (40, 60, 80))
        xs = np.nonzero(_changed(photo, branding.watermark(photo)))[1]
        return (xs.max() - xs.min() + 1) / w

    assert abs(mark_width(800, 600) - mark_width(3200, 2400)) < 0.01


def test_watermark_leaves_original_alone():
    photo = Image.new("RGB", (400, 300), (40, 60, 80))
    branding.watermark(photo)
    assert not np.any(np.asarray(photo) != 40 * np.array([1, 1.5, 2]))


def test_png_says_generated_by_tensorroom(tmp_path):
    image = Image.new("RGB", (32, 32))
    for loaded in (Image.open(io.BytesIO(branding.png_bytes(image))), _saved(image, tmp_path / "out.png")):
        assert loaded.info["Software"] == "TensorRoom"
        assert "Generated by TensorRoom" in loaded.info["Description"]
        assert "compositeWithTrainedAlgorithmicMedia" in loaded.info["XML:com.adobe.xmp"]


def _saved(image, path):
    branding.save_png(image, path)
    return Image.open(path)
