"""
Output branding: watermark and metadata
=======================================

What this file does
-------------------
Marks every edited image TensorRoom hands out:

``watermark(image)``
    Burns ``public/watermark.png`` into the bottom-right corner, scaled to
    ``branding.watermark_width`` of the image's width so it looks the same
    on a 1600 px preview and a 3072 px original.

``png_bytes(image)`` / ``save_png(image, path)``
    Write a PNG that says it was generated by TensorRoom: ``Software``,
    ``Description`` and ``Comment`` text chunks, plus XMP marking it as
    "composite with trained algorithmic media" (the IPTC term for a photo
    partly redrawn by AI), which photo apps and content checkers read.

Why the watermark is not stored on the session
----------------------------------------------
The worker keeps the clean result for "Keep editing". If the watermark were
burned into that copy, paste-back would carry it into the next edit and the
next result would get a second one on top. So it is applied only where an
image leaves the worker: the saved file, the display copy and ``/image``.
"""

from __future__ import annotations

import io
from functools import lru_cache
from pathlib import Path

from PIL import Image, PngImagePlugin

from src.config import load_config, repo_path

SOFTWARE = "TensorRoom"
DESCRIPTION = "Generated by TensorRoom: a room photo with selected objects redrawn by Qwen-Image-2.1."

# IPTC digital source type for a real photo with AI-generated parts.
_XMP = """<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:Iptc4xmpExt="http://iptc.org/std/Iptc4xmpExt/2008-02-29/"
    xmp:CreatorTool="TensorRoom"
    Iptc4xmpExt:DigitalSourceType="http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia">
   <dc:description><rdf:Alt><rdf:li xml:lang="x-default">{description}</rdf:li></rdf:Alt></dc:description>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"""


def _cfg() -> dict:
    return load_config().get("branding") or {}


@lru_cache(maxsize=4)
def _load_mark(path: str) -> Image.Image:
    return Image.open(path).convert("RGBA")


def watermark(image: Image.Image) -> Image.Image:
    """Return a copy of ``image`` with the watermark in the bottom-right corner."""
    cfg = _cfg()
    path = Path(repo_path(cfg.get("watermark", "public/watermark.png")))
    if not cfg.get("watermark_enabled", True) or not path.exists():
        return image.copy()

    mark = _load_mark(str(path))
    width = max(24, round(image.width * cfg.get("watermark_width", 0.08)))
    height = max(1, round(mark.height * width / mark.width))
    mark = mark.resize((width, height), Image.LANCZOS)
    opacity = cfg.get("watermark_opacity", 1.0)
    if opacity != 1.0:
        mark.putalpha(mark.getchannel("A").point(lambda a: min(255, round(a * opacity))))

    margin = round(min(image.size) * cfg.get("watermark_margin", 0.02))
    out = image.convert("RGBA")
    out.alpha_composite(mark, (max(0, out.width - width - margin), max(0, out.height - height - margin)))
    return out.convert(image.mode) if image.mode in ("RGB", "L") else out


def png_info() -> PngImagePlugin.PngInfo:
    """PNG text chunks saying the image was generated by TensorRoom."""
    info = PngImagePlugin.PngInfo()
    info.add_text("Software", SOFTWARE)
    info.add_text("Description", DESCRIPTION)
    info.add_text("Comment", DESCRIPTION)
    info.add_itxt("XML:com.adobe.xmp", _XMP.format(description=DESCRIPTION))
    return info


def png_bytes(image: Image.Image) -> bytes:
    buf = io.BytesIO()
    image.save(buf, format="PNG", pnginfo=png_info())
    return buf.getvalue()


def save_png(image: Image.Image, path: str | Path) -> None:
    image.save(path, format="PNG", pnginfo=png_info())
